import Head from "next/head";
import Link from "next/link";
import { GraphQLClient } from "graphql-request";

export async function getStaticProps() {
  const graphcms = new GraphQLClient(
    "https://api-eu-central-1.graphcms.com/v2/ck8sn5tnf01gc01z89dbc7s0o/master"
  );

  const { products } = await graphcms.request(
    `
      { 
        products {
          slug
          name
        }
      }
    `
  );

  return {
    props: {
      products
    }
  };
}

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>
          Create Next App {process.env.NEXT_PUBLIC_STORE_DOMAIN_NAME}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {products.map(({ slug, name }) => (
            <Link key={slug} href={`/products/${slug}`}>
              <a>{name}</a>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}
